wandb_version: 1

number_chargelevels:
  desc: null
  value: 26
number_spatial_nodes:
  desc: null
  value: 5
dataset:
  desc: null
  value: data/SF_5_clustered/SF_5_short_afternoon_test.json
episodes:
  desc: null
  value: 16000
number_vehicles_per_node_init:
  desc: null
  value: 1345
charging_stations:
  desc: null
  value:
  - true
  - true
  - true
  - true
  - true
charging_station_capacities:
  desc: null
  value:
  - 575.0
  - 1472.0
  - 2124.0
  - 785.0
  - 950.0
learning_rate_actor:
  desc: null
  value: 0.001
learning_rate_critic:
  desc: null
  value: 0.001
gradient_norm_clip_actor:
  desc: null
  value: 0.5
gradient_norm_clip_critic:
  desc: null
  value: 0.5
scale_factor:
  desc: null
  value: 0.01
scale_price:
  desc: null
  value: 0.1
time_horizon:
  desc: null
  value: 10
episode_length:
  desc: null
  value: 16
seed:
  desc: null
  value: 10
charge_levels_per_timestep:
  desc: null
  value: 16
licence:
  desc: null
  value: Karthik2
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685866409.708805
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
